# 默认配置
PHP_VERSION="8.4.12"
MYSQL_VERSION="8.4.0"
NGINX_VERSION="1.28.0"
REDIS_VERSION="7.2.4"
REDIS_PHP_EXT_VERSION="6.1.0"
IMAGICK_PHP_EXT_VERSION="3.7.0"
SWOOLE_PHP_EXT_VERSION="6.0.2"

# 安装路径
PHP_PREFIX="/usr/local/php"
MYSQL_PREFIX="/usr/local/mysql"
NGINX_PREFIX="/usr/local/nginx"
REDIS_PREFIX="/usr/local/redis"

# 用户配置
WWW_USER="www"
WWW_GROUP="www"
WWW_PASSWORD="CdOs491592."

# MySQL配置
MYSQL_ROOT_PASSWORD=""
MYSQL_REMOTE_ADMIN_USER=""
MYSQL_REMOTE_ADMIN_PASSWORD=""

# Redis配置
REDIS_PASSWORD=""

# 系统配置
SWAP_SIZE="2G"
INSTALL_DIR="/usr/local/src"
